repos:
  - repo: local
    hooks:
      - id: backend-ruff-check
        name: backend ruff check
        entry: bash -lc 'cd backend && uv run check'
        language: system
        pass_filenames: false
        files: ^backend/.*\.(py|pyi)$|^backend/(pyproject\.toml|uv\.lock)$

  - repo: local
    hooks:
      - id: frontend-check
        name: eslint check
        entry: bash -c 'cd frontend && pnpm run lint'
        language: system
        pass_filenames: false
        files: ^frontend/src/
