/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const createAclEntryRequestSchemaResourceTypeMax = 64;

export const createAclEntryRequestSchemaEffectMax = 16;

export const CreateAclEntryRequestSchema = zod.object({
  resourceType: zod
    .string()
    .min(1)
    .max(createAclEntryRequestSchemaResourceTypeMax),
  resourceId: zod.number(),
  permissionId: zod.number(),
  subjectPrincipalId: zod.number().nullish(),
  subjectRoleId: zod.number().nullish(),
  effect: zod.string().min(1).max(createAclEntryRequestSchemaEffectMax),
});
