/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const createPermissionRequestSchemaCodeMin = 3;
export const createPermissionRequestSchemaCodeMax = 128;

export const createPermissionRequestSchemaResourceTypeMax = 64;

export const createPermissionRequestSchemaActionMax = 64;

export const createPermissionRequestSchemaDescriptionDefault = ``;
export const createPermissionRequestSchemaDescriptionMax = 255;

export const CreatePermissionRequestSchema = zod.object({
  code: zod
    .string()
    .min(createPermissionRequestSchemaCodeMin)
    .max(createPermissionRequestSchemaCodeMax),
  resourceType: zod
    .string()
    .min(1)
    .max(createPermissionRequestSchemaResourceTypeMax),
  action: zod.string().min(1).max(createPermissionRequestSchemaActionMax),
  description: zod
    .string()
    .max(createPermissionRequestSchemaDescriptionMax)
    .default(createPermissionRequestSchemaDescriptionDefault),
});
