/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const createMembershipRequestSchemaStatusDefault = `active`;
export const createMembershipRequestSchemaStatusMax = 32;

export const CreateMembershipRequestSchema = zod.object({
  principalId: zod.number(),
  status: zod
    .string()
    .min(1)
    .max(createMembershipRequestSchemaStatusMax)
    .default(createMembershipRequestSchemaStatusDefault),
});
