/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const createAgentRequestSchemaCodeMin = 2;
export const createAgentRequestSchemaCodeMax = 64;

export const createAgentRequestSchemaDisplayNameMax = 128;

export const createAgentRequestSchemaDescriptionDefault = ``;
export const createAgentRequestSchemaDescriptionMax = 4000;

export const CreateAgentRequestSchema = zod.object({
  code: zod
    .string()
    .min(createAgentRequestSchemaCodeMin)
    .max(createAgentRequestSchemaCodeMax)
    .describe('Stable unique agent code'),
  displayName: zod
    .string()
    .min(1)
    .max(createAgentRequestSchemaDisplayNameMax)
    .describe('Display name'),
  description: zod
    .string()
    .max(createAgentRequestSchemaDescriptionMax)
    .default(createAgentRequestSchemaDescriptionDefault),
  avatarUrl: zod.string().nullish(),
  ownerPrincipalId: zod.number().nullish(),
});
