/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const createRoleRequestSchemaCodeMin = 2;
export const createRoleRequestSchemaCodeMax = 64;

export const createRoleRequestSchemaNameMax = 128;

export const createRoleRequestSchemaDescriptionDefault = ``;
export const createRoleRequestSchemaDescriptionMax = 255;

export const CreateRoleRequestSchema = zod.object({
  code: zod
    .string()
    .min(createRoleRequestSchemaCodeMin)
    .max(createRoleRequestSchemaCodeMax),
  name: zod.string().min(1).max(createRoleRequestSchemaNameMax),
  description: zod
    .string()
    .max(createRoleRequestSchemaDescriptionMax)
    .default(createRoleRequestSchemaDescriptionDefault),
});
