/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const createTenantRequestSchemaSlugMin = 2;
export const createTenantRequestSchemaSlugMax = 64;

export const createTenantRequestSchemaNameMax = 128;

export const CreateTenantRequestSchema = zod.object({
  slug: zod
    .string()
    .min(createTenantRequestSchemaSlugMin)
    .max(createTenantRequestSchemaSlugMax)
    .describe('Tenant slug'),
  name: zod.string().min(1).max(createTenantRequestSchemaNameMax),
});
