/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const loginRequestSchemaUsernameMin = 3;
export const loginRequestSchemaUsernameMax = 20;

export const loginRequestSchemaPasswordMin = 6;
export const loginRequestSchemaPasswordMax = 20;

export const LoginRequestSchema = zod.object({
  username: zod
    .string()
    .min(loginRequestSchemaUsernameMin)
    .max(loginRequestSchemaUsernameMax)
    .describe('Username'),
  password: zod
    .string()
    .min(loginRequestSchemaPasswordMin)
    .max(loginRequestSchemaPasswordMax)
    .describe('Password'),
});
