/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const loginRequestSchemaUsernameMin = 3;
export const loginRequestSchemaUsernameMax = 32;

export const loginRequestSchemaPasswordMin = 6;
export const loginRequestSchemaPasswordMax = 100;

export const LoginRequestSchema = zod
  .object({
    username: zod
      .string()
      .min(loginRequestSchemaUsernameMin)
      .max(loginRequestSchemaUsernameMax),
    password: zod
      .string()
      .min(loginRequestSchemaPasswordMin)
      .max(loginRequestSchemaPasswordMax),
  })
  .describe('Request body for username/password login.');
