/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const RefreshRequestSchema = zod.object({
  refreshToken: zod.string().describe('Opaque refresh token'),
});
