/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const registerRequestSchemaUsernameMin = 3;
export const registerRequestSchemaUsernameMax = 20;

export const registerRequestSchemaPasswordMin = 6;
export const registerRequestSchemaPasswordMax = 20;

export const RegisterRequestSchema = zod.object({
  username: zod
    .string()
    .min(registerRequestSchemaUsernameMin)
    .max(registerRequestSchemaUsernameMax)
    .describe('Username'),
  password: zod
    .string()
    .min(registerRequestSchemaPasswordMin)
    .max(registerRequestSchemaPasswordMax)
    .describe('Password'),
});
