/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const resetPasswordRequestSchemaNewPasswordMin = 6;
export const resetPasswordRequestSchemaNewPasswordMax = 100;

export const ResetPasswordRequestSchema = zod.object({
  "new_password": zod.string().min(resetPasswordRequestSchemaNewPasswordMin).max(resetPasswordRequestSchemaNewPasswordMax).describe('New password')
})
