/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const updateTenantRequestSchemaSlugMin = 2;
export const updateTenantRequestSchemaSlugMax = 64;

export const updateTenantRequestSchemaNameMax = 128;

export const UpdateTenantRequestSchema = zod.object({
  slug: zod
    .string()
    .min(updateTenantRequestSchemaSlugMin)
    .max(updateTenantRequestSchemaSlugMax)
    .nullish(),
  name: zod.string().min(1).max(updateTenantRequestSchemaNameMax).nullish(),
  isActive: zod.boolean().nullish(),
});
