/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const updateAgentRequestSchemaDisplayNameMax = 128;

export const updateAgentRequestSchemaDescriptionMax = 4000;

export const UpdateAgentRequestSchema = zod.object({
  displayName: zod
    .string()
    .min(1)
    .max(updateAgentRequestSchemaDisplayNameMax)
    .nullish(),
  description: zod
    .string()
    .max(updateAgentRequestSchemaDescriptionMax)
    .nullish(),
  avatarUrl: zod.string().nullish(),
});
