/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const updateUserSettingsRequestSchemaLocaleMin = 2;
export const updateUserSettingsRequestSchemaLocaleMax = 32;

export const updateUserSettingsRequestSchemaThemeMin = 2;
export const updateUserSettingsRequestSchemaThemeMax = 32;

export const updateUserSettingsRequestSchemaSystemPromptMax = 4000;

export const updateUserSettingsRequestSchemaDefaultModelMax = 128;

export const UpdateUserSettingsRequestSchema = zod
  .object({
    locale: zod
      .string()
      .min(updateUserSettingsRequestSchemaLocaleMin)
      .max(updateUserSettingsRequestSchemaLocaleMax)
      .nullish(),
    theme: zod
      .string()
      .min(updateUserSettingsRequestSchemaThemeMin)
      .max(updateUserSettingsRequestSchemaThemeMax)
      .nullish(),
    systemPrompt: zod
      .string()
      .max(updateUserSettingsRequestSchemaSystemPromptMax)
      .nullish(),
    defaultModel: zod
      .string()
      .min(1)
      .max(updateUserSettingsRequestSchemaDefaultModelMax)
      .nullish(),
  })
  .describe('Request body for user-settings updates.');
