/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const updatePermissionRequestSchemaCodeMin = 3;
export const updatePermissionRequestSchemaCodeMax = 128;

export const updatePermissionRequestSchemaResourceTypeMax = 64;

export const updatePermissionRequestSchemaActionMax = 64;

export const updatePermissionRequestSchemaDescriptionMax = 255;

export const UpdatePermissionRequestSchema = zod.object({
  code: zod
    .string()
    .min(updatePermissionRequestSchemaCodeMin)
    .max(updatePermissionRequestSchemaCodeMax)
    .nullish(),
  resourceType: zod
    .string()
    .min(1)
    .max(updatePermissionRequestSchemaResourceTypeMax)
    .nullish(),
  action: zod
    .string()
    .min(1)
    .max(updatePermissionRequestSchemaActionMax)
    .nullish(),
  description: zod
    .string()
    .max(updatePermissionRequestSchemaDescriptionMax)
    .nullish(),
});
