/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const updateRoleRequestSchemaCodeMin = 2;
export const updateRoleRequestSchemaCodeMax = 64;

export const updateRoleRequestSchemaNameMax = 128;

export const updateRoleRequestSchemaDescriptionMax = 255;

export const UpdateRoleRequestSchema = zod.object({
  code: zod
    .string()
    .min(updateRoleRequestSchemaCodeMin)
    .max(updateRoleRequestSchemaCodeMax)
    .nullish(),
  name: zod.string().min(1).max(updateRoleRequestSchemaNameMax).nullish(),
  description: zod
    .string()
    .max(updateRoleRequestSchemaDescriptionMax)
    .nullish(),
});
