/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const updateAclEntryRequestSchemaEffectMax = 16;

export const UpdateAclEntryRequestSchema = zod.object({
  permissionId: zod.number().nullish(),
  subjectPrincipalId: zod.number().nullish(),
  subjectRoleId: zod.number().nullish(),
  effect: zod
    .string()
    .min(1)
    .max(updateAclEntryRequestSchemaEffectMax)
    .nullish(),
});
