/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const UploadAvatarRequestSchema = zod.object({
  avatarUrl: zod.string().describe('Avatar URL'),
});
