/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const uploadAvatarRequestSchemaAvatarUrlMax = 2083;

export const UploadAvatarRequestSchema = zod.object({
  "avatar_url": zod.string().url().min(1).max(uploadAvatarRequestSchemaAvatarUrlMax).describe('Avatar URL')
})
