/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const userCreateSchemaUsernameMin = 3;
export const userCreateSchemaUsernameMax = 50;

export const userCreateSchemaPasswordMin = 6;
export const userCreateSchemaPasswordMax = 100;

export const UserCreateSchema = zod.object({
  username: zod
    .string()
    .min(userCreateSchemaUsernameMin)
    .max(userCreateSchemaUsernameMax)
    .describe('Username'),
  password: zod
    .string()
    .min(userCreateSchemaPasswordMin)
    .max(userCreateSchemaPasswordMax)
    .describe('Password'),
});
