import fs from 'node:fs/promises';
import path from 'node:path';

export const API_DIR = path.resolve('src/api');
export const TMP_DIR = path.join(API_DIR, '.orval');
export const MODELS_DIR = path.join(API_DIR, 'models');
export const MODELS_REQ_DIR = path.join(MODELS_DIR, 'req');
export const MODELS_RESP_DIR = path.join(MODELS_DIR, 'resp');
export const OPERATIONS_DIR = path.join(API_DIR, 'operations');
export const SCHEMAS_DIR = path.join(API_DIR, 'schemas');
export const OPENAPI_PATH = path.resolve('../docs/api/openapi.json');

const GENERATED_HEADER = `/**
 * Generated by frontend API sync.
 * Do not edit manually.
 */
`;

export async function exists(targetPath) {
  try {
    await fs.stat(targetPath);
    return true;
  } catch {
    return false;
  }
}

export async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

export async function readJson(filePath) {
  const source = await fs.readFile(filePath, 'utf8');
  return JSON.parse(source);
}

export function renderGeneratedFile(body) {
  const normalizedBody = body.replace(/^\n+/, '').trimEnd();
  return `${GENERATED_HEADER}\n${normalizedBody}\n`;
}

export async function listTsModules(dir) {
  if (!(await exists(dir))) {
    return [];
  }

  const entries = await fs.readdir(dir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.ts'))
    .map((entry) => entry.name.replace(/\.ts$/, ''))
    .filter((name) => name !== 'index')
    .sort();
}

export function renderBarrel(modules) {
  const body = modules.map((moduleName) => `export * from './${moduleName}';`);
  return renderGeneratedFile(body.join('\n'));
}

export async function reconcileBarrel(dir) {
  await ensureDir(dir);
  const modules = await listTsModules(dir);
  const indexPath = path.join(dir, 'index.ts');
  await fs.writeFile(indexPath, renderBarrel(modules), 'utf8');
}
