import fs from 'node:fs/promises';
import path from 'node:path';

import {
  exists,
  MODELS_REQ_DIR,
  MODELS_RESP_DIR,
  OPERATIONS_DIR,
  reconcileBarrel,
  SCHEMAS_DIR,
  TMP_DIR,
} from './codegen-utils.mjs';

async function stripZodInputTypes(dir) {
  if (!(await exists(dir))) return;

  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) {
      await stripZodInputTypes(p);
      continue;
    }
    if (!e.isFile() || !p.endsWith('.ts')) continue;

    const src = await fs.readFile(p, 'utf8');
    // Remove lines like: export type XxxSchema = zod.input<typeof XxxSchema>;
    const next = src
      .replace(/^\s*export type\s+\w+\s*=\s*zod\.input<[^>]+>;\s*\n/gm, '')
      .replace(/\n{3,}/g, '\n\n');

    if (next !== src) await fs.writeFile(p, next, 'utf8');
  }
}

async function stripEscapedForwardSlashes(dir) {
  if (!(await exists(dir))) return;

  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const filePath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await stripEscapedForwardSlashes(filePath);
      continue;
    }
    if (!entry.isFile() || !filePath.endsWith('.ts')) continue;

    const source = await fs.readFile(filePath, 'utf8');
    const nextSource = source.replaceAll('\\/', '/');
    if (nextSource !== source) {
      await fs.writeFile(filePath, nextSource, 'utf8');
    }
  }
}

async function writeResultType() {
  await fs.mkdir(MODELS_RESP_DIR, { recursive: true });

  const out = path.join(MODELS_RESP_DIR, 'result.ts');

  const content = `/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Result wrapper for service layer operations
 *
 * Encapsulates success/failure of an operation along with data or error information.
 *
 * Attributes:
 *     success: Indicates if the operation was successful
 *     data: The result data if successful, otherwise None
 *     code: Error code if failed, "0" if successful
 *     message: Error message if failed, "Success" if successful
 */
export type Result<T> = {
  code: string;
  message: string;
  data: T | null;
  success: boolean;
};
`;

  await fs.writeFile(out, content, 'utf8');
}

async function removeTmpTargets() {
  if (await exists(TMP_DIR)) {
    await fs.rm(TMP_DIR, { recursive: true, force: true });
  }
}

/**
 * Normalize Zod schema file names and update barrel imports.
 *
 * Rules:
 * 1) Remove "-schema" before extension:
 *    "user-create-schema.zod.ts" -> "user-create.zod.ts"
 * 2) Remove ".zod" marker:
 *    "user-create.zod.ts" -> "user-create.ts"
 */
async function renameSchemaFiles(dir) {
  if (!(await exists(dir))) return;

  // 1) 先做重命名
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const renames = [];

  for (const e of entries) {
    if (!e.isFile()) continue;

    const oldName = e.name;

    // remove "-schema" right before ".zod.ts"
    let newName = oldName.replace(/-schema(?=\.zod\.ts$)/, '');
    // remove ".zod" marker: "*.zod.ts" -> "*.ts"
    newName = newName.replace(/\.zod\.ts$/, '.ts');

    if (newName !== oldName) {
      renames.push({ oldName, newName });
      await fs.rename(path.join(dir, oldName), path.join(dir, newName));
    }
  }

  // 2) 没有重命名就结束
  if (renames.length === 0) return;

  // 3) 重命名后重新读取目录，避免拿到旧文件名（比如 index.zod.ts）
  const entriesAfter = await fs.readdir(dir, { withFileTypes: true });

  // 只更新真实存在的 index*.ts
  const indexFiles = entriesAfter.filter(
    (e) => e.isFile() && /^index(\..+)?\.ts$/.test(e.name),
  );

  for (const idx of indexFiles) {
    const p = path.join(dir, idx.name);
    let src = await fs.readFile(p, 'utf8');

    for (const { oldName, newName } of renames) {
      const oldModule = oldName.replace(/\.ts$/, '');
      const newModule = newName.replace(/\.ts$/, '');
      src = src.replaceAll(oldModule, newModule);
    }

    await fs.writeFile(p, src, 'utf8');
  }
}

await stripZodInputTypes(SCHEMAS_DIR);
await stripEscapedForwardSlashes(SCHEMAS_DIR);
await renameSchemaFiles(SCHEMAS_DIR);
await writeResultType();
await reconcileBarrel(MODELS_REQ_DIR);
await reconcileBarrel(MODELS_RESP_DIR);
await reconcileBarrel(SCHEMAS_DIR);
await reconcileBarrel(OPERATIONS_DIR);
await removeTmpTargets();
