import fs from 'node:fs/promises';
import path from 'node:path';

const TMP_DIR = path.resolve('src/api/.orval');
const SCHEMAS_DIR = path.resolve('src/api/schemas');
const MODELS_RESP_DIR = path.resolve('src/api/models/resp');

async function exists(p) {
  try {
    await fs.stat(p);
    return true;
  } catch {
    return false;
  }
}

async function stripZodInputTypes(dir) {
  if (!(await exists(dir))) return;

  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) {
      await stripZodInputTypes(p);
      continue;
    }
    if (!e.isFile() || !p.endsWith('.ts')) continue;

    const src = await fs.readFile(p, 'utf8');
    // Remove lines like: export type XxxSchema = zod.input<typeof XxxSchema>;
    const next = src
      .replace(/^\s*export type\s+\w+\s*=\s*zod\.input<[^>]+>;\s*\n/gm, '')
      .replace(/\n{3,}/g, '\n\n');

    if (next !== src) await fs.writeFile(p, next, 'utf8');
  }
}

async function writeResultType() {
  await fs.mkdir(MODELS_RESP_DIR, { recursive: true });

  const out = path.join(MODELS_RESP_DIR, 'result.ts');

  const content = `/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Result wrapper for service layer operations
 *
 * Encapsulates success/failure of an operation along with data or error information.
 *
 * Attributes:
 *     success: Indicates if the operation was successful
 *     data: The result data if successful, otherwise None
 *     code: Error code if failed, "0" if successful
 *     message: Error message if failed, "Success" if successful
 */
export type Result<T> = {
  code: string;
  message: string;
  data: T | null;
  success: boolean;
};
`;

  await fs.writeFile(out, content, 'utf8');
}

async function removeTmpTargets() {
  if (await exists(TMP_DIR)) {
    await fs.rm(TMP_DIR, { recursive: true, force: true });
  }
}

/**
 * Remove "-schema" from Zod schema file names and update barrel imports.
 * e.g. "user-create-schema.zod.ts" → "user-create.zod.ts"
 */
async function renameSchemaFiles(dir) {
  if (!(await exists(dir))) return;

  const entries = await fs.readdir(dir, { withFileTypes: true });
  const renames = [];

  for (const e of entries) {
    if (!e.isFile()) continue;
    const oldName = e.name;
    const newName = oldName.replace(/-schema(\.zod\.ts)$/, '$1');
    if (newName !== oldName) {
      renames.push({ oldName, newName });
      await fs.rename(path.join(dir, oldName), path.join(dir, newName));
    }
  }

  // Update barrel index if it exists
  if (renames.length === 0) return;
  const indexFiles = entries.filter(
    (e) => e.isFile() && e.name.startsWith('index'),
  );
  for (const idx of indexFiles) {
    const p = path.join(dir, idx.name);
    let src = await fs.readFile(p, 'utf8');
    for (const { oldName, newName } of renames) {
      const oldModule = oldName.replace(/\.ts$/, '');
      const newModule = newName.replace(/\.ts$/, '');
      src = src.replaceAll(oldModule, newModule);
    }
    await fs.writeFile(p, src, 'utf8');
  }
}

await stripZodInputTypes(SCHEMAS_DIR);
await renameSchemaFiles(SCHEMAS_DIR);
await writeResultType();
await removeTmpTargets();
