/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface AgentAccountResponse {
  principalId: number;
  ownerPrincipalId?: number | null;
  code: string;
  avatarUrl?: string;
  description?: string;
  displayName: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}
