/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { UserSettingsResponse } from './user-settings-response';
import type { UserSummaryResponse } from './user-summary-response';

/**
 * Response body containing user info plus opaque auth tokens.
 */
export interface AuthTokenResponse {
  user: UserSummaryResponse;
  settings: UserSettingsResponse;
  /** Opaque access token */
  accessToken: string;
  /** Opaque refresh token */
  refreshToken: string;
}
