/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { AgentAccountResponse } from './agent-account-response';
import type { TenantSummaryResponse } from './tenant-summary-response';
import type { UserAccountResponse } from './user-account-response';

export interface AuthTokenResponse {
  /** Authenticated user account */
  user?: UserAccountResponse | null;
  /** Authenticated agent account */
  agent?: AgentAccountResponse | null;
  /** Active tenant */
  tenant: TenantSummaryResponse;
  /** Opaque access token */
  accessToken: string;
  /** Opaque refresh token */
  refreshToken: string;
}
