/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { AgentAccountResponse } from './agent-account-response';
import type { PrincipalResponse } from './principal-response';
import type { TenantSummaryResponse } from './tenant-summary-response';
import type { UserAccountResponse } from './user-account-response';

export interface AuthMeResponse {
  principal: PrincipalResponse;
  tenant: TenantSummaryResponse;
  user?: UserAccountResponse | null;
  agent?: AgentAccountResponse | null;
}
