/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { UserInfoResponse } from './user-info-response';

/**
 * Authentication response schema

Contains user information and token returned after successful login or registration.

Attributes:
    user: User information (sanitized)
    token: JWT access token
 */
export interface AuthResponse {
  /** User information */
  user: UserInfoResponse;
  /** JWT access token */
  token: string;
}
