/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Readiness details for the health endpoint.
 */
export interface HealthResponse {
  db: boolean;
  redis: boolean;
}
