/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface PrincipalResponse {
  id: number;
  principalType: string;
  displayName: string;
  isActive: boolean;
  sessionVersion: number;
  authzVersion: number;
  createdAt: string;
  updatedAt: string;
}
