/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Runtime state snapshot returned by the debug endpoint.
 */
export interface RuntimeDebugResponse {
  state: string;
  debug: boolean;
  bootstrapEnabled: boolean;
  dbReady: boolean;
  redisReady: boolean;
}
