/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serialized view of an active auth session.
 */
export interface SessionInfoResponse {
  id: number;
  userAgent: string;
  ipAddress: string;
  expiresAt: string;
  lastSeenAt?: string | null;
  createdAt: string;
}
