/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * User response schema (sanitized)

User information returned to client, does not contain sensitive information.

Attributes:
    id: User ID
    avatar: Avatar URL
    role: User role
    is_active: Is active
 */
export interface UserResponse {
  /**
   * Username
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** User ID */
  id: number;
  /** Avatar URL */
  avatar?: string;
  /** User role */
  role?: string;
  /** Is active */
  is_active?: boolean;
}
