/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface UserAccountResponse {
  principalId: number;
  username: string;
  avatarUrl?: string;
  bio?: string;
  gender?: string | null;
  dateOfBirth?: string | null;
  timezone?: string | null;
  displayName: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}
