/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * User info and Token returned after successful login

Inherits UserResponse and Token, contains complete user info and token.
 */
export interface UserWithToken {
  /** JWT access token */
  accessToken: string;
  /** Token type */
  tokenType?: string;
  /**
   * Username
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** User ID */
  id: number;
  /** Avatar URL */
  avatar?: string;
  /** User role */
  role?: string;
  /** Is active */
  isActive?: boolean;
}
