/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serialized view of a user profile.
 */
export interface UserSummaryResponse {
  id: number;
  username: string;
  displayName: string;
  avatarUrl: string;
  bio: string;
  timezone?: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}
