/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serialized view of user preference settings.
 */
export interface UserSettingsResponse {
  locale: string;
  theme: string;
  systemPrompt: string;
  defaultModel: string;
}
