/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface ChangeAgentOwnerRequest {
  ownerPrincipalId?: number | null;
}
