/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePermissionRequest {
  /**
   * @minLength 3
   * @maxLength 128
   */
  code: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  resourceType: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  action: string;
  /** @maxLength 255 */
  description?: string;
}
