/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateAgentRequest {
  /**
   * Stable unique agent code
   * @minLength 2
   * @maxLength 64
   */
  code: string;
  /**
   * Display name
   * @minLength 1
   * @maxLength 128
   */
  displayName: string;
  /** @maxLength 4000 */
  description?: string;
  avatarUrl?: string | null;
  ownerPrincipalId?: number | null;
}
