/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTenantRequest {
  /**
   * Tenant slug
   * @minLength 2
   * @maxLength 64
   */
  slug: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  name: string;
}
