/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request body for refresh-token rotation.
 */
export interface RefreshRequest {
  /** Opaque refresh token */
  refreshToken: string;
}
