/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  /**
   * Username
   * @minLength 3
   * @maxLength 20
   */
  username: string;
  /**
   * Password
   * @minLength 6
   * @maxLength 100
   */
  password: string;
  /**
   * Display name
   * @minLength 1
   * @maxLength 128
   */
  displayName?: string | null;
}
