/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request body for user self-registration.
 */
export interface RegisterRequest {
  /**
   * @minLength 3
   * @maxLength 32
   */
  username: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  displayName?: string | null;
}
