/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * FastAPI Auth App
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface ResetPasswordRequest {
  /**
   * New password
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string;
}
