/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request body for profile updates.
 */
export interface UpdateUserProfileRequest {
  /**
   * @minLength 1
   * @maxLength 128
   */
  displayName?: string | null;
  /** @maxLength 2000 */
  bio?: string | null;
  /**
   * @minLength 1
   * @maxLength 64
   */
  timezone?: string | null;
}
