/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTenantRequest {
  /**
   * @minLength 2
   * @maxLength 64
   */
  slug?: string | null;
  /**
   * @minLength 1
   * @maxLength 128
   */
  name?: string | null;
  isActive?: boolean | null;
}
