/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request body for user-settings updates.
 */
export interface UpdateUserSettingsRequest {
  /**
   * @minLength 2
   * @maxLength 32
   */
  locale?: string | null;
  /**
   * @minLength 2
   * @maxLength 32
   */
  theme?: string | null;
  /** @maxLength 4000 */
  systemPrompt?: string | null;
  /**
   * @minLength 1
   * @maxLength 128
   */
  defaultModel?: string | null;
}
