/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Ello Bot
 * Ello Bot Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateAgentRequest {
  /**
   * @minLength 1
   * @maxLength 128
   */
  displayName?: string | null;
  /** @maxLength 4000 */
  description?: string | null;
  avatarUrl?: string | null;
}
