/**
 * Generated by frontend API sync.
 * Do not edit manually.
 */

export type ApiOperationMethod =
  | 'delete'
  | 'get'
  | 'options'
  | 'patch'
  | 'post'
  | 'put';

export type ApiOperationContract<
  TResponse = unknown,
  TRequest = undefined,
  TMethod extends ApiOperationMethod = ApiOperationMethod,
  TPath extends string = string,
> = {
  readonly id: string;
  readonly method: TMethod;
  readonly path: TPath;
  readonly __responseType?: TResponse;
  readonly __requestType?: TRequest;
};

export type ApiOperationResponse<TOperation extends ApiOperationContract> =
  TOperation extends ApiOperationContract<
    infer TResponse,
    unknown,
    ApiOperationMethod,
    string
  >
    ? TResponse
    : never;

export type ApiOperationRequest<TOperation extends ApiOperationContract> =
  TOperation extends ApiOperationContract<
    unknown,
    infer TRequest,
    ApiOperationMethod,
    string
  >
    ? TRequest
    : never;

export const defineApiOperation = <
  TResponse,
  TRequest = void,
  TMethod extends ApiOperationMethod = ApiOperationMethod,
  TPath extends string = string,
>(operation: {
  id: string;
  method: TMethod;
  path: TPath;
}): ApiOperationContract<TResponse, TRequest, TMethod, TPath> =>
  operation as ApiOperationContract<TResponse, TRequest, TMethod, TPath>;
