/**
 * Generated by frontend API sync.
 * Do not edit manually.
 */

import type { RuntimeDebugResponse } from '../models/resp';

import { defineApiOperation } from './api-operation';

export const runtimeStatusOperation = defineApiOperation<
  RuntimeDebugResponse,
  void,
  'get',
  '/api/debug/runtime'
>({
  id: 'runtime_status_api_debug_runtime_get',
  method: 'get',
  path: '/api/debug/runtime',
});

export const debugOperations = {
  runtimeStatus: runtimeStatusOperation,
} as const;
