/**
 * Generated by frontend API sync.
 * Do not edit manually.
 */

import type { HealthResponse } from '../models/resp';

import { defineApiOperation } from './api-operation';

export const healthOperation = defineApiOperation<
  HealthResponse,
  void,
  'get',
  '/health'
>({
  id: 'health_health_get',
  method: 'get',
  path: '/health',
});

export const healthOperations = {
  health: healthOperation,
} as const;
