/**
 * Generated by frontend API sync.
 * Do not edit manually.
 */

import type {
  LoginRequest,
  RefreshRequest,
  RegisterRequest,
} from '../models/req';
import type { AuthTokenResponse, SessionInfoResponse } from '../models/resp';

import { defineApiOperation } from './api-operation';

export const listSessionsOperation = defineApiOperation<
  SessionInfoResponse[],
  void,
  'get',
  '/api/sessions/list'
>({
  id: 'list_sessions_api_sessions_list_get',
  method: 'get',
  path: '/api/sessions/list',
});

export const loginOperation = defineApiOperation<
  AuthTokenResponse,
  LoginRequest,
  'post',
  '/api/sessions/login'
>({
  id: 'login_api_sessions_login_post',
  method: 'post',
  path: '/api/sessions/login',
});

export const logoutOperation = defineApiOperation<
  void,
  void,
  'post',
  '/api/sessions/logout'
>({
  id: 'logout_api_sessions_logout_post',
  method: 'post',
  path: '/api/sessions/logout',
});

export const logoutAllOperation = defineApiOperation<
  void,
  void,
  'post',
  '/api/sessions/logout-all'
>({
  id: 'logout_all_api_sessions_logout_all_post',
  method: 'post',
  path: '/api/sessions/logout-all',
});

export const refreshOperation = defineApiOperation<
  AuthTokenResponse,
  RefreshRequest,
  'post',
  '/api/sessions/refresh'
>({
  id: 'refresh_api_sessions_refresh_post',
  method: 'post',
  path: '/api/sessions/refresh',
});

export const registerOperation = defineApiOperation<
  AuthTokenResponse,
  RegisterRequest,
  'post',
  '/api/sessions/register'
>({
  id: 'register_api_sessions_register_post',
  method: 'post',
  path: '/api/sessions/register',
});

export const sessionsOperations = {
  listSessions: listSessionsOperation,
  login: loginOperation,
  logout: logoutOperation,
  logoutAll: logoutAllOperation,
  refresh: refreshOperation,
  register: registerOperation,
} as const;
