/**
 * Generated by frontend API sync.
 * Do not edit manually.
 */

import type {
  UpdateUserProfileRequest,
  UpdateUserSettingsRequest,
} from '../models/req';
import type {
  BootstrapAdminResponse,
  CurrentUserResponse,
  UserSettingsResponse,
  UserSummaryResponse,
} from '../models/resp';

import { defineApiOperation } from './api-operation';

export const getCurrentUserOperation = defineApiOperation<
  CurrentUserResponse,
  void,
  'get',
  '/api/user/get-current-user'
>({
  id: 'get_current_user_api_user_get_current_user_get',
  method: 'get',
  path: '/api/user/get-current-user',
});

export const getProfileOperation = defineApiOperation<
  UserSummaryResponse,
  void,
  'get',
  '/api/user/get-profile'
>({
  id: 'get_profile_api_user_get_profile_get',
  method: 'get',
  path: '/api/user/get-profile',
});

export const getSettingsOperation = defineApiOperation<
  UserSettingsResponse,
  void,
  'get',
  '/api/user/get-settings'
>({
  id: 'get_settings_api_user_get_settings_get',
  method: 'get',
  path: '/api/user/get-settings',
});

export const bootstrapAdminOperation = defineApiOperation<
  BootstrapAdminResponse,
  void,
  'post',
  '/api/user/bootstrap-admin'
>({
  id: 'bootstrap_admin_api_user_bootstrap_admin_post',
  method: 'post',
  path: '/api/user/bootstrap-admin',
});

export const updateProfileOperation = defineApiOperation<
  UserSummaryResponse,
  UpdateUserProfileRequest,
  'post',
  '/api/user/update-profile'
>({
  id: 'update_profile_api_user_update_profile_post',
  method: 'post',
  path: '/api/user/update-profile',
});

export const updateSettingsOperation = defineApiOperation<
  UserSettingsResponse,
  UpdateUserSettingsRequest,
  'post',
  '/api/user/update-settings'
>({
  id: 'update_settings_api_user_update_settings_post',
  method: 'post',
  path: '/api/user/update-settings',
});

export const userOperations = {
  getCurrentUser: getCurrentUserOperation,
  getProfile: getProfileOperation,
  getSettings: getSettingsOperation,
  bootstrapAdmin: bootstrapAdminOperation,
  updateProfile: updateProfileOperation,
  updateSettings: updateSettingsOperation,
} as const;
